channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - ipykernel=7.2.0
  - salib=1.5.2
  - zlib=1.3.1
  - r-base=4.5.2
  - r-essentials=4.5
  - r-devtools=2.4.6
  - r-remotes=2.5.0
  - r-tidyverse=2.0.0
  - r-xslt=1.5.1
  - r-ggrepel=0.9.6
  - r-lhs=1.2.0
  - r-gridextra=2.3
  - r-doparallel=1.0.17
  - r-xml=3.99_0.17
  - r-xml2=1.4.0
  - r-rsqlite=2.4.6
  - r-plogr=0.2.0
  - r-pak=0.9.2
  - r-nloptr=2.2.1
  - r-tictoc=1.2.1
  - r-lme4=1.1_38
  - r-future.apply=1.20.1
  - r-future=1.69.0
  - r-here=1.0.2
  - r-png=0.1_8
  - r-reticulate=1.44.1
  - r-rcpptoml=0.2.3
  - r-rjson=0.2.23
  - r-stringr=1.6.0
  - r-ggh4x=0.3.1